name: CI
on: [push]
jobs:
  linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '17.5.0'
          cache: 'yarn'
      - name: Cache c3d libraries
        uses: actions/cache@v2
        env:
          cache-name: cache-c3d-libraries
        with:
          path: Linux_Ubuntu_1804_GCC_7.4.0_Unicode.zip
          key: ${{ runner.os }}-build-${{ env.cache-name }}
      - name: Download c3d libraries
        run: |
          wget -q -N --user='${{ secrets.C3D_DOWNLOAD_USER }}' --password '${{ secrets.C3D_DOWNLOAD_PASS }}' https://c3d.sd.ascon.ru/C3D_workversion/V2022_WRK/C3D_Kernel/117658/Kernel/Linux_Ubuntu_1804_GCC_7.4.0_Unicode.zip
          7z x Linux_Ubuntu_1804_GCC_7.4.0_Unicode.zip -o'vendor/c3d/'
      - name: Setup license key
        run: |
          echo '${{ secrets.C3D_LICENSE_KEY_LINUX }}' > "license-key.json"
      - name: Yarn install
        run: |
          yarn install --frozen-lockfile
      - name: Cache C++ build
        id: cache-cpp-build
        uses: actions/cache@v2
        env:
          cache-name: cache-cpp-build
        with:
          path: build/Release
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('Linux_Ubuntu_1804_GCC_7.4.0_Unicode.zip', 'generate/api.mjs') }}
      - name: Codegen C++ and build
        run: |
          sudo apt-get -qq install astyle
          yarn generate
          yarn run node-gyp configure
          yarn electron-rebuild
      - name: Publish canary release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SNAPCRAFT_BUILD_ENVIRONMENT: host
        run: |
          sudo apt-get -qq install flatpak elfutils
          sudo snap install snapcraft --classic
          DEBUG='electron-forge-maker-snap:*,electron-forge:lifecycle' yarn publish
  increment-version:
    needs: [linux]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '17.5.0'
          cache: 'yarn'
      - name: Increment version
        run: |
          yarn plugin import version
          yarn version patch
          git config user.email "mr@roboto.com"
          git config user.name "GitHub Action"
          git commit -am "Update version"
          git push
